version: "3"
services:
  dada:
    image: ghcr.io/andreas-hofmann/dadamail
    container_name: dada_dada
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./data/dada:/opt/dada
    environment:
      DADA_ROOT_PASSWORD: iamdroot # Change this!
      DADA_URL: http://localhost:8080 # Adjust to your actually used URL. Include the protocol and port, if necessary.
    depends_on:
      db:
        condition: service_healthy
    networks:
      - database

  db:
    image: mariadb
    container_name: dada_mariadb
    restart: always
    ports:
      - "3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      database:
        aliases:
          - mysql
    environment:
      MARIADB_DATABASE: dada
      MARIADB_USER: dada
      MARIADB_PASSWORD: dada_dada
      MARIADB_RANDOM_ROOT_PASSWORD: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  database:

